openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/tutorial/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /student/{student_id}:
    get:
      summary: Gets a student
      description: Returns a single student
      operationId: get_student_by_id
      parameters:
      - name: student_id
        in: path
        description: The unique student id
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Student'
              examples:
                student:
                  value:
                    student_id: 123
                    first_name: John
                    last_name: Doe
                    grade_records:
                    - subject_name: Mathematics
                      grade: 8.5
        "400":
          description: Invalid ID supplied
        "404":
          description: Student not found
      x-openapi-router-controller: swagger_server.controllers.default_controller
    delete:
      summary: Deletes a student
      description: |
        Deletes a single student based on the provided student_id.
      operationId: delete_student
      parameters:
      - name: student_id
        in: path
        description: The unique student id
        required: true
        style: simple
        explode: false
        schema:
          type: number
          format: integer
      responses:
        "200":
          description: Student successfully deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request - Invalid student id supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_400'
        "404":
          description: Not Found - Student with the specified student_id cannot be
            found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_404'
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /student:
    post:
      summary: Add a new student
      description: Adds a student to the system
      operationId: add_student
      requestBody:
        description: Student object to add
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
            examples:
              newStudent:
                value:
                  first_name: Jane
                  last_name: Doe
                  student_id: 456
                  grade_records:
                  - subject_name: History
                    grade: 9
        required: true
      responses:
        "200":
          description: Student created
          content:
            application/json:
              schema:
                type: string
                format: uuid
                x-content-type: application/json
              examples:
                created:
                  value: 550e8400-e29b-41d4-a716-446655440000
        "400":
          description: "Invalid input, object invalid"
        "409":
          description: Student already exists
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Student:
      required:
      - first_name
      - last_name
      type: object
      properties:
        student_id:
          type: number
          format: integer
          example: 123
        first_name:
          type: string
          example: John
        last_name:
          type: string
          example: Doe
        grade_records:
          type: array
          example:
          - subject_name: Mathematics
            grade: 8.5
          items:
            $ref: '#/components/schemas/GradeRecord'
      example:
        student_id: 123
        last_name: Doe
        grade_records:
        - subject_name: Mathematics
          grade: 8.5
        first_name: John
    GradeRecord:
      required:
      - grade
      - subject_name
      type: object
      properties:
        subject_name:
          type: string
          example: Mathematics
        grade:
          maximum: 10
          minimum: 0
          type: number
          format: float
          example: 8.5
    inline_response_200:
      type: object
      properties:
        message:
          type: string
          example: Student deleted successfully.
      example:
        message: Student deleted successfully.
    inline_response_400:
      type: object
      properties:
        error:
          type: string
          example: The provided student_id is invalid.
    inline_response_404:
      type: object
      properties:
        error:
          type: string
          example: Student not found.

